import productRouter from "./productRouter.js";
import supplierRouter from "./supplierRouter.js";
import productTypeRouter from "./productTypeRouter.js";
import unitRouter from "./unitRouter.js";
import authRouter from "./authRouter.js";
import serviceRouter from "./serviceRouter.js";
import inventoryReportRouter from "./inventoryReportRouter.js";
import serviceOrdersRouter from "./serviceOrdersRouter.js";
import salesOrderDetailsRouter from "./salesOrderDetailsRouter.js";
import serviceOrderDetailsRouter from "./serviceOrderDetailsRouter.js";
import inventoryReportDetailsRouter from "./inventoryReportDetailsRouter.js";
import purchaseOrderDetailRouter from "./purchaseOrderDetailRouter.js";
import purchaseOrdersRouter from "./purchaseOrdersRouter.js";
import salesOrdersRouter from "./salesOrdersRouter.js";
import cartRouter from "./cartRouter.js";
export const routes = (app) => {
  app.use("/api/products", productRouter);
  app.use("/api/suppliers", supplierRouter);
  app.use("/api/product-types", productTypeRouter);
  app.use("/api/units", unitRouter);
  app.use("/api/auth", authRouter);
  app.use("/api/services", serviceRouter);
  app.use("/api/inventory-reports", inventoryReportRouter);
  app.use("/api/service-orders", serviceOrdersRouter);
  app.use("/api/sales-order-details", salesOrderDetailsRouter);
  app.use("/api/service-order-details", serviceOrderDetailsRouter);
  app.use("/api/inventory-reports-details", inventoryReportDetailsRouter);
  app.use("/api/purchase-orders", purchaseOrdersRouter);
  app.use("/api/sales-orders", salesOrdersRouter);
  app.use("/api/purchase-order-details", purchaseOrderDetailRouter);
  app.use("/api/carts", cartRouter);
};
